spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/BusinessCard
    username: user5Y5
    password: EYfSyfQiEQ3mUlNx
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect